### ISSUE TITLE
Error 500 happens when logging into freshly cleaned base

### ISSUE THREAD

**Issue by phorward** [viur-framework/base#3]
![image](https://user-images.githubusercontent.com/16870072/37031533-71048fba-213f-11e8-82f7-88b49d29b7a2.png)
This error happens because the template user_login_success.html calls the undefined function icon() to render a "check mark" icon. I think this issue belongs to a function that was planned to become part of the server but was not merged yet.

**Comment by phorward** [comment]
Login via http://localhost:8080/user/auth_userpassword/login

**Comment by sveneberth** [comment]
fixed in [#5](https://github.com/viur-framework/base/pull/5)
